"""empty message

Revision ID: 10beb94563f
Revises: None
Create Date: 2015-09-27 10:12:42.427327

"""

# revision identifiers, used by Alembic.
revision = '10beb94563f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('generation_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    ### end Alembic commands ###
