"""empty message

Revision ID: 4887d7d44d6
Revises: None
Create Date: 2015-10-09 02:53:30.559553

"""

# revision identifiers, used by Alembic.
revision = '4887d7d44d6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('generation_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    ### end Alembic commands ###
